### ISSUE TITLE
glslc Windows 64 Android SDK

### ISSUE THREAD

**Issue by vitalfadeev** [DannyArends/CalderaD#6]
I was installed Android SDK, run search "glslc" and not found any. Test, please, and fix readme.

**Comment by vitalfadeev** [comment]
Test this: https://github.com/google/shaderc/blob/main/downloads.md
glslc inside

**Comment by DannyArends** [comment]
Hey vitalfadeev,

Thanks for your comment. You're right, the glslc compiler is included in the NDK (not the SDK). I've updated the README.md file, it now reads:

"_To compile the shaders, install the glslc compiler from [LunarG Vulkan SDK](https://vulkan.lunarg.com/), a glslc compiler is also included in the shader-tools/windows-x86_64 folder of the Android Native Development Kit (NDK) which [Android Studio](https://developer.android.com/studio) can install for you (see [here](https://developer.android.com/studio/projects/install-ndk))._"

The link to google/shaderc repository contains the explicit warning:

'Note: These binaries are just the artifacts of the builders and have not undergone any QA, thus they should be considered unsupported.'

So I'd rather not advice people to use those.

Did you get the example working on windows x64 / Android ?
